### ISSUE TITLE
SimpleRanker needs update

### ISSUE THREAD

**Issue by ugm2** [jina-ai/executors#321]
In [jinahub/rankers/SimpleRanker/simpleranker.py#L48](https://github.com/jina-ai/executors/blob/41b5cf875682dfd582550d85645ab5ada5fb26d7/jinahub/rankers/SimpleRanker/simpleranker.py#L82) it fails here:

```
File "/home/unai/.jina/hub-packages/4mq3egay/simpleranker.py", line 83, in rank
    for m in DocumentArray([doc]).traverse_flat(['cm']):
  File "/home/unai/personal/annual-report-intelligent-search/.venv/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 121, in traverse_flat
    return self._flatten(leaves)
  File "/home/unai/personal/annual-report-intelligent-search/.venv/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 160, in _flatten
    return DocumentArray(list(itertools.chain.from_iterable(sequence)))
  File "/home/unai/personal/annual-report-intelligent-search/.venv/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 45, in traverse
    for p in traversal_paths.split(','):
AttributeError: 'list' object has no attribute 'split'
```

It seems it needs updating to support latest changes in Docarray.

After manually bypassing that error (by passing a string instead of a list), I'm getting the following one:
```
File "/home/unai/.jina/hub-packages/4mq3egay/simpleranker.py", line 104, in rank
    doc.matches.sort(key=lambda d: d.scores[self.metric].value)
AttributeError: 'MatchArray' object has no attribute 'sort'
``` 

[jinahub/rankers/SimpleRanker/simpleranker.py#L103](https://github.com/jina-ai/executors/blob/41b5cf875682dfd582550d85645ab5ada5fb26d7/jinahub/rankers/SimpleRanker/simpleranker.py#L103)

Which also seems like it needs updating to support latest changes in Docarray.

**Comment by JoanFM** [comment]
Thanks for reporting, will do!

**Comment by samsja** [comment]
Hey @ugm2 we just updated the simpleranker executor to work with jina 3.0 ( in this PR https://github.com/jina-ai/executor-simpleranker/pull/3)
